builds:
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
archives:
  replacements:
    amd64: x86_64
  name_template: "{{ .ProjectName }}.{{ .Os }}.{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
